export const cargoItems = [
  {
    title: 'Musical Instruments',
    des: 'Violins, trumpets, and saxophones',
    weight: 9,
    height: 19,
    length: 13,
    width: 35,
    pis: 1,
    extra: false,
  },
  {
    title: 'Sports Equipment',
    des: 'Bats, balls, and sports gear',
    weight: 29,
    height: 9,
    length: 70,
    width: 60,
    pis: 1,
    extra: false,
  },
  {
    title: 'Electrical Appliances',
    des: 'Washing machines, dishwashers, and more',
    weight: 36,
    height: 13,
    length: 17,
    width: 57,
    pis: 1,
    extra: false,
  },
  {
    title: 'Medical Equipment',
    des: 'Hospital beds, medical devices, and supplies',
    weight: 24,
    height: 6,
    length: 85,
    width: 22,
    pis: 1,
    extra: true,
  },
  {
    title: 'Art Supplies',
    des: 'Paints, canvases, and art tools',
    weight: 14,
    height: 18,
    length: 60,
    width: 60,
    pis: 1,
    extra: false,
  },
  {
    title: 'Gym Equipment',
    des: 'Treadmills, weights, and exercise machines',
    weight: 38,
    height: 22,
    length: 4,
    width: 35,
    pis: 1,
    extra: false,
  },
  {
    title: 'Holiday Decorations',
    des: 'Christmas trees, ornaments, and decorations',
    weight: 39,
    height: 20,
    length: 90,
    width: 53,
    pis: 1,
    extra: false,
  },
  {
    title: 'Motorcycles',
    des: 'Motorbikes and motorcycle accessories',
    weight: 3,
    height: 21,
    length: 96,
    width: 50,
    pis: 1,
    extra: false,
  },
  {
    title: 'Jewelry Safe',
    des: 'A secure safe for valuable jewelry',
    weight: 7,
    height: 4,
    length: 18,
    width: 4,
    pis: 1,
    extra: false,
  },
  {
    title: 'Firewood',
    des: 'Stacks of firewood for the winter',
    weight: 24,
    height: 8,
    length: 46,
    width: 48,
    pis: 1,
    extra: true,
  },
  {
    title: 'Construction Tools',
    des: 'Power tools and construction machinery',
    weight: 35,
    height: 10,
    length: 54,
    width: 8,
    pis: 1,
    extra: false,
  },
  {
    title: 'Surfboards',
    des: 'Surfboards and beach gear',
    weight: 11,
    height: 8,
    length: 75,
    width: 20,
    pis: 1,
    extra: true,
  },
  {
    title: 'Vintage Cars',
    des: 'Antique automobiles and car parts',
    weight: 28,
    height: 22,
    length: 24,
    width: 51,
    pis: 1,
    extra: false,
  },
  {
    title: 'Camping Gear',
    des: 'Tents, sleeping bags, and camping equipment',
    weight: 5,
    height: 11,
    length: 67,
    width: 4,
    pis: 1,
    extra: false,
  },
  {
    title: 'Astronomical Telescopes',
    des: 'High-powered telescopes for stargazing',
    weight: 35,
    height: 1,
    length: 25,
    width: 57,
    pis: 1,
    extra: false,
  },
  {
    title: 'Rare Coins',
    des: 'Collection of rare and valuable coins',
    weight: 3,
    height: 7,
    length: 98,
    width: 45,
    pis: 1,
    extra: false,
  },
  {
    title: 'Musical Records',
    des: 'Vinyl records and record players',
    weight: 16,
    height: 29,
    length: 69,
    width: 35,
    pis: 1,
    extra: false,
  },
  {
    title: 'Pool Tables',
    des: 'Billiard tables and equipment',
    weight: 18,
    height: 5,
    length: 6,
    width: 4,
    pis: 1,
    extra: false,
  },
  {
    title: 'Collectible Figurines',
    des: 'Limited edition figurines and collectibles',
    weight: 37,
    height: 19,
    length: 59,
    width: 8,
    pis: 1,
    extra: true,
  },
  {
    title: 'Furniture',
    des: 'Various pieces of furniture',
    weight: 1,
    height: 23,
    length: 91,
    width: 28,
    pis: 1,
    extra: false,
  },
  {
    title: 'Boxes',
    des: 'Assorted cardboard boxes',
    weight: 31,
    height: 14,
    length: 78,
    width: 38,
    pis: 1,
    extra: false,
  },
  {
    title: 'Appliances',
    des: 'Household appliances',
    weight: 13,
    height: 14,
    length: 60,
    width: 58,
    pis: 1,
    extra: false,
  },
  {
    title: 'Musical Instruments',
    des: 'Violins, trumpets, and saxophones',
    weight: 19,
    height: 29,
    length: 71,
    width: 8,
    pis: 1,
    extra: true,
  },
  {
    title: 'Sports Equipment',
    des: 'Bats, balls, and sports gear',
    weight: 34,
    height: 8,
    length: 68,
    width: 25,
    pis: 1,
    extra: false,
  },
  {
    title: 'Electrical Appliances',
    des: 'Washing machines, dishwashers, and more',
    weight: 25,
    height: 14,
    length: 90,
    width: 54,
    pis: 1,
    extra: true,
  },
  {
    title: 'Medical Equipment',
    des: 'Hospital beds, medical devices, and supplies',
    weight: 4,
    height: 20,
    length: 38,
    width: 48,
    pis: 1,
    extra: false,
  },
  {
    title: 'Art Supplies',
    des: 'Paints, canvases, and art tools',
    weight: 38,
    height: 18,
    length: 7,
    width: 3,
    pis: 1,
    extra: false,
  },
  {
    title: 'Gym Equipment',
    des: 'Treadmills, weights, and exercise machines',
    weight: 4,
    height: 11,
    length: 94,
    width: 23,
    pis: 1,
    extra: false,
  },
  {
    title: 'Holiday Decorations',
    des: 'Christmas trees, ornaments, and decorations',
    weight: 21,
    height: 30,
    length: 43,
    width: 44,
    pis: 1,
    extra: false,
  },
  {
    title: 'Motorcycles',
    des: 'Motorbikes and motorcycle accessories',
    weight: 10,
    height: 22,
    length: 79,
    width: 52,
    pis: 1,
    extra: true,
  },
  {
    title: 'Jewelry Safe',
    des: 'A secure safe for valuable jewelry',
    weight: 27,
    height: 22,
    length: 2,
    width: 52,
    pis: 1,
    extra: true,
  },
  {
    title: 'Firewood',
    des: 'Stacks of firewood for the winter',
    weight: 7,
    height: 17,
    length: 83,
    width: 24,
    pis: 1,
    extra: false,
  },
  {
    title: 'Construction Tools',
    des: 'Power tools and construction machinery',
    weight: 25,
    height: 2,
    length: 93,
    width: 30,
    pis: 1,
    extra: true,
  },
  {
    title: 'Surfboards',
    des: 'Surfboards and beach gear',
    weight: 20,
    height: 19,
    length: 62,
    width: 24,
    pis: 1,
    extra: false,
  },
  {
    title: 'Vintage Cars',
    des: 'Antique automobiles and car parts',
    weight: 25,
    height: 16,
    length: 20,
    width: 33,
    pis: 1,
    extra: true,
  },
  {
    title: 'Furniture',
    des: 'Various pieces of furniture',
    weight: 4,
    height: 15,
    length: 34,
    width: 52,
    pis: 1,
    extra: false,
  },
  {
    title: 'Boxes',
    des: 'Assorted cardboard boxes',
    weight: 17,
    height: 27,
    length: 54,
    width: 11,
    pis: 1,
    extra: false,
  },
  {
    title: 'Appliances',
    des: 'Household appliances',
    weight: 8,
    height: 7,
    length: 86,
    width: 32,
    pis: 1,
    extra: false,
  },
  {
    title: 'Electronics',
    des: 'TVs, computers, and gadgets',
    weight: 33,
    height: 7,
    length: 56,
    width: 10,
    pis: 1,
    extra: false,
  },
  {
    title: 'Books',
    des: 'Book collection',
    weight: 33,
    height: 5,
    length: 96,
    width: 19,
    pis: 1,
    extra: true,
  },
  {
    title: 'Clothing',
    des: 'Clothes and garments',
    weight: 31,
    height: 4,
    length: 58,
    width: 48,
    pis: 1,
    extra: false,
  },
  {
    title: 'Antiques',
    des: 'Valuable antiques',
    weight: 1,
    height: 7,
    length: 49,
    width: 48,
    pis: 1,
    extra: false,
  },
  {
    title: 'Fish Tanks',
    des: 'Fish tanks and aquarium equipment',
    weight: 39,
    height: 6,
    length: 67,
    width: 27,
    pis: 1,
    extra: true,
  },
  {
    title: 'Food Items',
    des: 'Assorted food items and groceries',
    weight: 12,
    height: 6,
    length: 12,
    width: 19,
    pis: 1,
    extra: true,
  },
  {
    title: 'Construction Materials',
    des: 'Building supplies and materials',
    weight: 38,
    height: 2,
    length: 62,
    width: 3,
    pis: 1,
    extra: false,
  },
  {
    title: 'Plants',
    des: 'Indoor and outdoor plants and gardening supplies',
    weight: 1,
    height: 20,
    length: 53,
    width: 28,
    pis: 1,
    extra: true,
  },
  {
    title: 'Sporting Equipment',
    des: 'Sports gear and equipment',
    weight: 18,
    height: 5,
    length: 30,
    width: 20,
    pis: 1,
    extra: true,
  },
  {
    title: 'Artwork',
    des: 'Paintings and sculptures',
    weight: 9,
    height: 1,
    length: 60,
    width: 49,
    pis: 1,
    extra: false,
  },
  {
    title: 'Musical Instruments',
    des: 'Instruments like pianos and guitars',
    weight: 24,
    height: 14,
    length: 25,
    width: 8,
    pis: 1,
    extra: false,
  },
  {
    title: 'Kitchen Appliances',
    des: 'Ovens, refrigerators, and more',
    weight: 6,
    height: 28,
    length: 9,
    width: 16,
    pis: 1,
    extra: false,
  },
  {
    title: 'Office Supplies',
    des: 'Desks, chairs, and office equipment',
    weight: 4,
    height: 15,
    length: 86,
    width: 14,
    pis: 1,
    extra: false,
  },
  {
    title: 'Toys',
    des: "Children's toys and games",
    weight: 30,
    height: 11,
    length: 48,
    width: 42,
    pis: 1,
    extra: false,
  },
  {
    title: 'Gardening Tools',
    des: 'Shovels, rakes, and gardening equipment',
    weight: 22,
    height: 26,
    length: 90,
    width: 53,
    pis: 1,
    extra: false,
  },
  {
    title: 'Bicycles',
    des: 'Bikes and cycling gear',
    weight: 26,
    height: 14,
    length: 60,
    width: 41,
    pis: 1,
    extra: false,
  },
  {
    title: 'Pet Supplies',
    des: 'Pet food, cages, and accessories',
    weight: 30,
    height: 2,
    length: 32,
    width: 22,
    pis: 1,
    extra: false,
  },
  {
    title: 'Camping Gear',
    des: 'Tents, sleeping bags, and camping equipment',
    weight: 19,
    height: 20,
    length: 91,
    width: 28,
    pis: 1,
    extra: false,
  },
  {
    title: 'Astronomical Telescopes',
    des: 'High-powered telescopes for stargazing',
    weight: 21,
    height: 7,
    length: 32,
    width: 27,
    pis: 1,
    extra: false,
  },
  {
    title: 'Rare Coins',
    des: 'Collection of rare and valuable coins',
    weight: 16,
    height: 23,
    length: 87,
    width: 11,
    pis: 1,
    extra: false,
  },
  {
    title: 'Musical Records',
    des: 'Vinyl records and record players',
    weight: 24,
    height: 19,
    length: 2,
    width: 58,
    pis: 1,
    extra: false,
  },
  {
    title: 'Pool Tables',
    des: 'Billiard tables and equipment',
    weight: 25,
    height: 15,
    length: 5,
    width: 38,
    pis: 1,
    extra: false,
  },
  {
    title: 'Collectible Figurines',
    des: 'Limited edition figurines and collectibles',
    weight: 40,
    height: 25,
    length: 97,
    width: 33,
    pis: 1,
    extra: true,
  },
  {
    title: 'Electronics',
    des: 'TVs, computers, and gadgets',
    weight: 22,
    height: 24,
    length: 15,
    width: 18,
    pis: 1,
    extra: true,
  },
  {
    title: 'Books',
    des: 'Book collection',
    weight: 21,
    height: 7,
    length: 41,
    width: 30,
    pis: 1,
    extra: false,
  },
  {
    title: 'Clothing',
    des: 'Clothes and garments',
    weight: 19,
    height: 29,
    length: 66,
    width: 4,
    pis: 1,
    extra: false,
  },
  {
    title: 'Antiques',
    des: 'Valuable antiques',
    weight: 17,
    height: 6,
    length: 65,
    width: 8,
    pis: 1,
    extra: false,
  },
  {
    title: 'Fish Tanks',
    des: 'Fish tanks and aquarium equipment',
    weight: 35,
    height: 11,
    length: 24,
    width: 23,
    pis: 1,
    extra: false,
  },
  {
    title: 'Food Items',
    des: 'Assorted food items and groceries',
    weight: 12,
    height: 13,
    length: 44,
    width: 21,
    pis: 1,
    extra: false,
  },
  {
    title: 'Construction Materials',
    des: 'Building supplies and materials',
    weight: 2,
    height: 8,
    length: 62,
    width: 43,
    pis: 1,
    extra: false,
  },
  {
    title: 'Plants',
    des: 'Indoor and outdoor plants and gardening supplies',
    weight: 39,
    height: 10,
    length: 56,
    width: 51,
    pis: 1,
    extra: false,
  },
  {
    title: 'Sporting Equipment',
    des: 'Sports gear and equipment',
    weight: 15,
    height: 8,
    length: 21,
    width: 54,
    pis: 1,
    extra: false,
  },
  {
    title: 'Artwork',
    des: 'Paintings and sculptures',
    weight: 16,
    height: 23,
    length: 34,
    width: 14,
    pis: 1,
    extra: true,
  },
  {
    title: 'Kitchen Appliances',
    des: 'Ovens, refrigerators, and more',
    weight: 36,
    height: 15,
    length: 10,
    width: 3,
    pis: 1,
    extra: false,
  },
  {
    title: 'Office Supplies',
    des: 'Desks, chairs, and office equipment',
    weight: 23,
    height: 23,
    length: 5,
    width: 1,
    pis: 1,
    extra: false,
  },
  {
    title: 'Toys',
    des: "Children's toys and games",
    weight: 34,
    height: 10,
    length: 30,
    width: 46,
    pis: 1,
    extra: false,
  },
  {
    title: 'Gardening Tools',
    des: 'Shovels, rakes, and gardening equipment',
    weight: 24,
    height: 8,
    length: 93,
    width: 52,
    pis: 1,
    extra: true,
  },
  {
    title: 'Bicycles',
    des: 'Bikes and cycling gear',
    weight: 3,
    height: 4,
    length: 25,
    width: 2,
    pis: 1,
    extra: true,
  },
  {
    title: 'Pet Supplies',
    des: 'Pet food, cages, and accessories',
    weight: 20,
    height: 11,
    length: 86,
    width: 3,
    pis: 1,
    extra: true,
  },
];
